[profile.default]
src = "src"
out = "out"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
libs = ["lib"]

[profile.sepolia]
rpc_url = "https://arb-sepolia.g.alchemy.com/v2/3Gu3LVJ8RwwCRbk0o75gH"
chain_id = 421614
gas_price = 1000000000

[profile.arbitrum_sepolia]
rpc_url = "https://arb-sepolia.g.alchemy.com/v2/3Gu3LVJ8RwwCRbk0o75gH"
chain_id = 421614
etherscan_api_key = "${ARBISCAN_API_KEY}"
gas_price = 1000000000
